import type { User, Formation, Session, Registration } from "@shared/schema";

// TODO: remove mock functionality - Demo users for authentication
export const mockUsers: User[] = [
  {
    id: "1",
    email: "marie.dupont@colombus.com",
    password: "demo",
    name: "Marie Dupont",
    roles: ["consultant"],
    seniority: "confirme",
    businessUnit: "Digital",
    p1Used: 0,
    p2Used: 1,
    archived: false,
  },
  {
    id: "2",
    email: "sophie.martin@colombus.com",
    password: "demo",
    name: "Sophie Martin",
    roles: ["consultant", "rh"],
    seniority: null,
    businessUnit: "RH",
    p1Used: 0,
    p2Used: 0,
    archived: false,
  },
  {
    id: "3",
    email: "pierre.bernard@colombus.com",
    password: "demo",
    name: "Pierre Bernard",
    roles: ["consultant", "formateur"],
    seniority: "expert",
    businessUnit: "Tech",
    p1Used: 0,
    p2Used: 0,
    archived: false,
  },
  {
    id: "5",
    email: "claire.leroux@colombus.com",
    password: "demo",
    name: "Claire Leroux",
    roles: ["formateur_externe"],
    seniority: "senior",
    businessUnit: "Partenaire externe",
    p1Used: 0,
    p2Used: 0,
    archived: false,
  },
  {
    id: "4",
    email: "julie.rousseau@colombus.com",
    password: "demo",
    name: "Julie Rousseau",
    roles: ["consultant", "manager"],
    seniority: "senior",
    businessUnit: "Consulting",
    p1Used: 0,
    p2Used: 0,
    archived: false,
  },
];

// TODO: remove mock functionality - Sample formations
export const mockFormations: Formation[] = [
  {
    id: "f1",
    title: "Méthodologie Agile Scrum",
    description: "Découvrez les principes fondamentaux de la méthodologie Agile et du framework Scrum pour gérer vos projets de manière itérative et collaborative.",
    objectives: "Comprendre les valeurs Agile, maîtriser les cérémonies Scrum, appliquer les bonnes pratiques",
    prerequisites: "Aucun prérequis",
    duration: "2 jours",
    modality: "presentiel",
    seniorityRequired: "junior",
    theme: "Gestion de projet",
    tags: ["agile", "scrum", "gestion projet"],
    active: true,
  },
  {
    id: "f2",
    title: "Leadership et Management d'Équipe",
    description: "Développez vos compétences en leadership pour manager efficacement vos équipes et créer un environnement de travail positif.",
    objectives: "Développer son style de leadership, motiver ses équipes, gérer les conflits",
    prerequisites: "Expérience en management souhaitée",
    duration: "3 jours",
    modality: "hybride",
    seniorityRequired: "confirme",
    theme: "Management",
    tags: ["leadership", "management", "soft skills"],
    active: true,
  },
  {
    id: "f3",
    title: "Data Science avec Python",
    description: "Formation intensive sur l'analyse de données et le machine learning avec Python, pandas, scikit-learn et TensorFlow.",
    objectives: "Maîtriser pandas, créer des modèles ML, visualiser les données",
    prerequisites: "Connaissance de base en Python",
    duration: "5 jours",
    modality: "distanciel",
    seniorityRequired: "confirme",
    theme: "Technique",
    tags: ["python", "data science", "machine learning"],
    active: true,
  },
  {
    id: "f4",
    title: "Communication Efficace en Entreprise",
    description: "Améliorez vos compétences en communication orale et écrite pour être plus impactant dans vos interactions professionnelles.",
    objectives: "Structurer ses messages, adapter sa communication, gérer les situations délicates",
    prerequisites: "Aucun prérequis",
    duration: "1 jour",
    modality: "presentiel",
    seniorityRequired: "junior",
    theme: "Soft Skills",
    tags: ["communication", "soft skills"],
    active: true,
  },
  {
    id: "f5",
    title: "Architecture Cloud AWS",
    description: "Formation avancée sur la conception et l'implémentation d'architectures cloud sur Amazon Web Services.",
    objectives: "Concevoir des architectures scalables, optimiser les coûts, sécuriser les infrastructures",
    prerequisites: "Expérience en infrastructure IT",
    duration: "4 jours",
    modality: "distanciel",
    seniorityRequired: "senior",
    theme: "Technique",
    tags: ["aws", "cloud", "architecture"],
    active: true,
  },
  {
    id: "f6",
    title: "Stratégie de Transformation Digitale",
    description: "Comprendre les enjeux de la transformation digitale et élaborer une stratégie adaptée à votre organisation.",
    objectives: "Identifier les opportunités digitales, piloter la transformation, mesurer les résultats",
    prerequisites: "Expérience en stratégie d'entreprise",
    duration: "2 jours",
    modality: "presentiel",
    seniorityRequired: "expert",
    theme: "Stratégie",
    tags: ["digital", "transformation", "stratégie"],
    active: true,
  },
];

// TODO: remove mock functionality - Sample sessions
export const mockSessions: Session[] = [
  {
    id: "s1",
    formationId: "f1",
    startDate: new Date("2025-11-15T09:00:00"),
    endDate: new Date("2025-11-16T17:00:00"),
    location: "Salle Paris - La Défense",
    capacity: 12,
    instructorId: "3",
    status: "open",
  },
  {
    id: "s2",
    formationId: "f1",
    startDate: new Date("2025-12-10T09:00:00"),
    endDate: new Date("2025-12-11T17:00:00"),
    location: "Salle Lyon Part-Dieu",
    capacity: 12,
    instructorId: "3",
    status: "open",
  },
  {
    id: "s3",
    formationId: "f2",
    startDate: new Date("2025-11-20T09:00:00"),
    endDate: new Date("2025-11-22T17:00:00"),
    location: "Salle Paris + Visio",
    capacity: 15,
    instructorId: "3",
    status: "open",
  },
  {
    id: "s4",
    formationId: "f3",
    startDate: new Date("2025-11-25T09:00:00"),
    endDate: new Date("2025-11-29T17:00:00"),
    location: "Visio Teams",
    capacity: 20,
    instructorId: "3",
    status: "open",
  },
  {
    id: "s5",
    formationId: "f4",
    startDate: new Date("2025-11-08T09:00:00"),
    endDate: new Date("2025-11-08T17:00:00"),
    location: "Salle Toulouse",
    capacity: 10,
    instructorId: "3",
    status: "full",
  },
];

// TODO: remove mock functionality - Sample registrations
export const mockRegistrations: Registration[] = [
  {
    id: "r1",
    userId: "1",
    sessionId: "s3",
    formationId: "f2",
    priority: "P2",
    status: "validated",
    registeredAt: new Date("2025-10-15T10:30:00"),
    attended: false,
  },
  {
    id: "r2",
    userId: "1",
    sessionId: "s4",
    formationId: "f3",
    priority: "P3",
    status: "pending",
    registeredAt: new Date("2025-10-20T14:00:00"),
    attended: false,
  },
];
